AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple serverless URL shortener

Globals:
  Function:
    Timeout: 5
    Runtime: python3.12

Resources:

  CreateShortUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/createShortUrl/index.lambda_handler
      CodeUri: .
      Environment:
        Variables:
          TABLE_NAME: UrlShortener
      Policies:
        - DynamoDBCrudPolicy:
            TableName: UrlShortener
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /shorten
            Method: POST

  RedirectFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/redirect/index.lambda_handler
      CodeUri: .
      Environment:
        Variables:
          TABLE_NAME: UrlShortener
      Policies:
        - DynamoDBCrudPolicy:
            TableName: UrlShortener
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{shortId}
            Method: GET

